# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'LabView.ui'
#
# Created: Thu May 10 21:39:42 2012
#      by: PyQt4 UI code generator 4.9
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1098, 799)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayout_53 = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_53.setObjectName(_fromUtf8("horizontalLayout_53"))
        self.verticalLayout_22 = QtGui.QVBoxLayout()
        self.verticalLayout_22.setObjectName(_fromUtf8("verticalLayout_22"))
        self.horizontalLayout_50 = QtGui.QHBoxLayout()
        self.horizontalLayout_50.setObjectName(_fromUtf8("horizontalLayout_50"))
        self.label_39 = QtGui.QLabel(self.centralwidget)
        self.label_39.setObjectName(_fromUtf8("label_39"))
        self.horizontalLayout_50.addWidget(self.label_39)
        spacerItem = QtGui.QSpacerItem(148, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_50.addItem(spacerItem)
        self.verticalLayout_22.addLayout(self.horizontalLayout_50)
        self.frame = QtGui.QFrame(self.centralwidget)
        self.frame.setMaximumSize(QtCore.QSize(321, 692))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.frame)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.toolBox = QtGui.QToolBox(self.frame)
        self.toolBox.setObjectName(_fromUtf8("toolBox"))
        self.page_5 = QtGui.QWidget()
        self.page_5.setGeometry(QtCore.QRect(0, 0, 295, 488))
        self.page_5.setObjectName(_fromUtf8("page_5"))
        self.verticalLayout_12 = QtGui.QVBoxLayout(self.page_5)
        self.verticalLayout_12.setObjectName(_fromUtf8("verticalLayout_12"))
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.label_28 = QtGui.QLabel(self.page_5)
        self.label_28.setMinimumSize(QtCore.QSize(91, 16))
        self.label_28.setMaximumSize(QtCore.QSize(91, 16))
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.horizontalLayout_13.addWidget(self.label_28)
        self.comboBox_2 = QtGui.QComboBox(self.page_5)
        self.comboBox_2.setMinimumSize(QtCore.QSize(131, 26))
        self.comboBox_2.setMaximumSize(QtCore.QSize(131, 26))
        self.comboBox_2.setObjectName(_fromUtf8("comboBox_2"))
        self.horizontalLayout_13.addWidget(self.comboBox_2)
        self.verticalLayout_12.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.label_27 = QtGui.QLabel(self.page_5)
        self.label_27.setMinimumSize(QtCore.QSize(91, 16))
        self.label_27.setMaximumSize(QtCore.QSize(91, 16))
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.horizontalLayout_14.addWidget(self.label_27)
        self.comboBox_3 = QtGui.QComboBox(self.page_5)
        self.comboBox_3.setMinimumSize(QtCore.QSize(131, 26))
        self.comboBox_3.setMaximumSize(QtCore.QSize(131, 26))
        self.comboBox_3.setObjectName(_fromUtf8("comboBox_3"))
        self.horizontalLayout_14.addWidget(self.comboBox_3)
        self.verticalLayout_12.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_20 = QtGui.QHBoxLayout()
        self.horizontalLayout_20.setObjectName(_fromUtf8("horizontalLayout_20"))
        self.label_37 = QtGui.QLabel(self.page_5)
        self.label_37.setMinimumSize(QtCore.QSize(91, 16))
        self.label_37.setMaximumSize(QtCore.QSize(91, 16))
        self.label_37.setObjectName(_fromUtf8("label_37"))
        self.horizontalLayout_20.addWidget(self.label_37)
        self.horizontalSlider = QtGui.QSlider(self.page_5)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName(_fromUtf8("horizontalSlider"))
        self.horizontalLayout_20.addWidget(self.horizontalSlider)
        self.doubleSpinBox = QtGui.QDoubleSpinBox(self.page_5)
        self.doubleSpinBox.setEnabled(False)
        self.doubleSpinBox.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.doubleSpinBox.setMaximum(1.0)
        self.doubleSpinBox.setSingleStep(0.1)
        self.doubleSpinBox.setObjectName(_fromUtf8("doubleSpinBox"))
        self.horizontalLayout_20.addWidget(self.doubleSpinBox)
        self.verticalLayout_12.addLayout(self.horizontalLayout_20)
        self.toolBox.addItem(self.page_5, _fromUtf8(""))
        self.page_6 = QtGui.QWidget()
        self.page_6.setGeometry(QtCore.QRect(0, 0, 295, 488))
        self.page_6.setObjectName(_fromUtf8("page_6"))
        self.verticalLayout_11 = QtGui.QVBoxLayout(self.page_6)
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        self.comboBox = QtGui.QComboBox(self.page_6)
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.verticalLayout_11.addWidget(self.comboBox)
        self.stackedWidget = QtGui.QStackedWidget(self.page_6)
        self.stackedWidget.setObjectName(_fromUtf8("stackedWidget"))
        self.page = QtGui.QWidget()
        self.page.setObjectName(_fromUtf8("page"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.page)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_2 = QtGui.QLabel(self.page)
        self.label_2.setMinimumSize(QtCore.QSize(98, 16))
        self.label_2.setMaximumSize(QtCore.QSize(98, 16))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_2.addWidget(self.label_2)
        self.spinBox = QtGui.QSpinBox(self.page)
        self.spinBox.setMaximum(20000)
        self.spinBox.setProperty("value", 20000)
        self.spinBox.setObjectName(_fromUtf8("spinBox"))
        self.horizontalLayout_2.addWidget(self.spinBox)
        self.label_3 = QtGui.QLabel(self.page)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_2.addWidget(self.label_3)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_4 = QtGui.QLabel(self.page)
        self.label_4.setMinimumSize(QtCore.QSize(98, 16))
        self.label_4.setMaximumSize(QtCore.QSize(98, 16))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout.addWidget(self.label_4)
        self.spinBox_2 = QtGui.QSpinBox(self.page)
        self.spinBox_2.setMaximum(20000)
        self.spinBox_2.setProperty("value", 20000)
        self.spinBox_2.setObjectName(_fromUtf8("spinBox_2"))
        self.horizontalLayout.addWidget(self.spinBox_2)
        self.label_5 = QtGui.QLabel(self.page)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout.addWidget(self.label_5)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_6 = QtGui.QLabel(self.page)
        self.label_6.setMinimumSize(QtCore.QSize(98, 16))
        self.label_6.setMaximumSize(QtCore.QSize(98, 16))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_3.addWidget(self.label_6)
        self.spinBox_3 = QtGui.QSpinBox(self.page)
        self.spinBox_3.setMaximum(20000)
        self.spinBox_3.setProperty("value", 20000)
        self.spinBox_3.setObjectName(_fromUtf8("spinBox_3"))
        self.horizontalLayout_3.addWidget(self.spinBox_3)
        self.label_7 = QtGui.QLabel(self.page)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout_3.addWidget(self.label_7)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtGui.QWidget()
        self.page_2.setObjectName(_fromUtf8("page_2"))
        self.verticalLayout = QtGui.QVBoxLayout(self.page_2)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_8 = QtGui.QLabel(self.page_2)
        self.label_8.setMinimumSize(QtCore.QSize(98, 16))
        self.label_8.setMaximumSize(QtCore.QSize(98, 16))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.horizontalLayout_4.addWidget(self.label_8)
        self.spinBox_4 = QtGui.QSpinBox(self.page_2)
        self.spinBox_4.setMinimumSize(QtCore.QSize(69, 25))
        self.spinBox_4.setMaximumSize(QtCore.QSize(69, 25))
        self.spinBox_4.setMaximum(20000)
        self.spinBox_4.setProperty("value", 20000)
        self.spinBox_4.setObjectName(_fromUtf8("spinBox_4"))
        self.horizontalLayout_4.addWidget(self.spinBox_4)
        self.label_9 = QtGui.QLabel(self.page_2)
        self.label_9.setMinimumSize(QtCore.QSize(17, 16))
        self.label_9.setMaximumSize(QtCore.QSize(17, 16))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.horizontalLayout_4.addWidget(self.label_9)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_10 = QtGui.QLabel(self.page_2)
        self.label_10.setMinimumSize(QtCore.QSize(98, 16))
        self.label_10.setMaximumSize(QtCore.QSize(98, 16))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.horizontalLayout_5.addWidget(self.label_10)
        self.spinBox_5 = QtGui.QSpinBox(self.page_2)
        self.spinBox_5.setMinimumSize(QtCore.QSize(69, 25))
        self.spinBox_5.setMaximumSize(QtCore.QSize(69, 25))
        self.spinBox_5.setMaximum(20000)
        self.spinBox_5.setProperty("value", 20000)
        self.spinBox_5.setObjectName(_fromUtf8("spinBox_5"))
        self.horizontalLayout_5.addWidget(self.spinBox_5)
        self.label_11 = QtGui.QLabel(self.page_2)
        self.label_11.setMinimumSize(QtCore.QSize(17, 16))
        self.label_11.setMaximumSize(QtCore.QSize(17, 16))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.horizontalLayout_5.addWidget(self.label_11)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.label_12 = QtGui.QLabel(self.page_2)
        self.label_12.setMinimumSize(QtCore.QSize(98, 16))
        self.label_12.setMaximumSize(QtCore.QSize(98, 16))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.horizontalLayout_6.addWidget(self.label_12)
        self.spinBox_6 = QtGui.QSpinBox(self.page_2)
        self.spinBox_6.setMinimumSize(QtCore.QSize(69, 25))
        self.spinBox_6.setMaximumSize(QtCore.QSize(69, 25))
        self.spinBox_6.setMaximum(20000)
        self.spinBox_6.setProperty("value", 20000)
        self.spinBox_6.setObjectName(_fromUtf8("spinBox_6"))
        self.horizontalLayout_6.addWidget(self.spinBox_6)
        self.label_13 = QtGui.QLabel(self.page_2)
        self.label_13.setMinimumSize(QtCore.QSize(17, 16))
        self.label_13.setMaximumSize(QtCore.QSize(17, 16))
        self.label_13.setText(_fromUtf8(""))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.horizontalLayout_6.addWidget(self.label_13)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QtGui.QWidget()
        self.page_3.setObjectName(_fromUtf8("page_3"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.page_3)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.label_14 = QtGui.QLabel(self.page_3)
        self.label_14.setMinimumSize(QtCore.QSize(98, 16))
        self.label_14.setMaximumSize(QtCore.QSize(98, 16))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.horizontalLayout_7.addWidget(self.label_14)
        self.spinBox_7 = QtGui.QSpinBox(self.page_3)
        self.spinBox_7.setMinimumSize(QtCore.QSize(69, 25))
        self.spinBox_7.setMaximumSize(QtCore.QSize(69, 25))
        self.spinBox_7.setMinimum(3)
        self.spinBox_7.setMaximum(18)
        self.spinBox_7.setProperty("value", 18)
        self.spinBox_7.setObjectName(_fromUtf8("spinBox_7"))
        self.horizontalLayout_7.addWidget(self.spinBox_7)
        self.label_15 = QtGui.QLabel(self.page_3)
        self.label_15.setMinimumSize(QtCore.QSize(17, 16))
        self.label_15.setMaximumSize(QtCore.QSize(17, 16))
        self.label_15.setText(_fromUtf8(""))
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.horizontalLayout_7.addWidget(self.label_15)
        self.verticalLayout_4.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.label_16 = QtGui.QLabel(self.page_3)
        self.label_16.setMinimumSize(QtCore.QSize(98, 16))
        self.label_16.setMaximumSize(QtCore.QSize(98, 16))
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.horizontalLayout_8.addWidget(self.label_16)
        self.spinBox_8 = QtGui.QSpinBox(self.page_3)
        self.spinBox_8.setMinimumSize(QtCore.QSize(69, 25))
        self.spinBox_8.setMaximumSize(QtCore.QSize(69, 25))
        self.spinBox_8.setMinimum(3)
        self.spinBox_8.setMaximum(18)
        self.spinBox_8.setProperty("value", 18)
        self.spinBox_8.setObjectName(_fromUtf8("spinBox_8"))
        self.horizontalLayout_8.addWidget(self.spinBox_8)
        self.label_17 = QtGui.QLabel(self.page_3)
        self.label_17.setMinimumSize(QtCore.QSize(17, 16))
        self.label_17.setMaximumSize(QtCore.QSize(17, 16))
        self.label_17.setText(_fromUtf8(""))
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.horizontalLayout_8.addWidget(self.label_17)
        self.verticalLayout_4.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.label_18 = QtGui.QLabel(self.page_3)
        self.label_18.setMinimumSize(QtCore.QSize(98, 16))
        self.label_18.setMaximumSize(QtCore.QSize(98, 16))
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.horizontalLayout_9.addWidget(self.label_18)
        self.spinBox_9 = QtGui.QSpinBox(self.page_3)
        self.spinBox_9.setEnabled(False)
        self.spinBox_9.setMinimumSize(QtCore.QSize(69, 25))
        self.spinBox_9.setMaximumSize(QtCore.QSize(69, 25))
        self.spinBox_9.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.spinBox_9.setMinimum(3)
        self.spinBox_9.setMaximum(18)
        self.spinBox_9.setProperty("value", 18)
        self.spinBox_9.setObjectName(_fromUtf8("spinBox_9"))
        self.horizontalLayout_9.addWidget(self.spinBox_9)
        self.label_19 = QtGui.QLabel(self.page_3)
        self.label_19.setMinimumSize(QtCore.QSize(17, 16))
        self.label_19.setMaximumSize(QtCore.QSize(17, 16))
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.horizontalLayout_9.addWidget(self.label_19)
        self.verticalLayout_4.addLayout(self.horizontalLayout_9)
        self.stackedWidget.addWidget(self.page_3)
        self.page_4 = QtGui.QWidget()
        self.page_4.setObjectName(_fromUtf8("page_4"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.page_4)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.label_22 = QtGui.QLabel(self.page_4)
        self.label_22.setMinimumSize(QtCore.QSize(98, 16))
        self.label_22.setMaximumSize(QtCore.QSize(98, 16))
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.horizontalLayout_11.addWidget(self.label_22)
        self.spinBox_11 = QtGui.QSpinBox(self.page_4)
        self.spinBox_11.setMinimumSize(QtCore.QSize(69, 25))
        self.spinBox_11.setMaximumSize(QtCore.QSize(69, 25))
        self.spinBox_11.setMinimum(3)
        self.spinBox_11.setMaximum(18)
        self.spinBox_11.setProperty("value", 18)
        self.spinBox_11.setObjectName(_fromUtf8("spinBox_11"))
        self.horizontalLayout_11.addWidget(self.spinBox_11)
        self.label_23 = QtGui.QLabel(self.page_4)
        self.label_23.setMinimumSize(QtCore.QSize(17, 16))
        self.label_23.setMaximumSize(QtCore.QSize(17, 16))
        self.label_23.setText(_fromUtf8(""))
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.horizontalLayout_11.addWidget(self.label_23)
        self.verticalLayout_3.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.label_20 = QtGui.QLabel(self.page_4)
        self.label_20.setMinimumSize(QtCore.QSize(98, 16))
        self.label_20.setMaximumSize(QtCore.QSize(98, 16))
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.horizontalLayout_10.addWidget(self.label_20)
        self.spinBox_10 = QtGui.QSpinBox(self.page_4)
        self.spinBox_10.setMinimumSize(QtCore.QSize(69, 25))
        self.spinBox_10.setMaximumSize(QtCore.QSize(69, 25))
        self.spinBox_10.setMinimum(3)
        self.spinBox_10.setMaximum(18)
        self.spinBox_10.setProperty("value", 18)
        self.spinBox_10.setObjectName(_fromUtf8("spinBox_10"))
        self.horizontalLayout_10.addWidget(self.spinBox_10)
        self.label_21 = QtGui.QLabel(self.page_4)
        self.label_21.setMinimumSize(QtCore.QSize(17, 16))
        self.label_21.setMaximumSize(QtCore.QSize(17, 16))
        self.label_21.setText(_fromUtf8(""))
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.horizontalLayout_10.addWidget(self.label_21)
        self.verticalLayout_3.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.label_24 = QtGui.QLabel(self.page_4)
        self.label_24.setMinimumSize(QtCore.QSize(98, 16))
        self.label_24.setMaximumSize(QtCore.QSize(98, 16))
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.horizontalLayout_12.addWidget(self.label_24)
        self.spinBox_12 = QtGui.QSpinBox(self.page_4)
        self.spinBox_12.setEnabled(False)
        self.spinBox_12.setMinimumSize(QtCore.QSize(69, 25))
        self.spinBox_12.setMaximumSize(QtCore.QSize(69, 25))
        self.spinBox_12.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.spinBox_12.setMinimum(3)
        self.spinBox_12.setMaximum(18)
        self.spinBox_12.setProperty("value", 18)
        self.spinBox_12.setObjectName(_fromUtf8("spinBox_12"))
        self.horizontalLayout_12.addWidget(self.spinBox_12)
        self.label_25 = QtGui.QLabel(self.page_4)
        self.label_25.setMinimumSize(QtCore.QSize(17, 16))
        self.label_25.setMaximumSize(QtCore.QSize(17, 16))
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.horizontalLayout_12.addWidget(self.label_25)
        self.verticalLayout_3.addLayout(self.horizontalLayout_12)
        self.stackedWidget.addWidget(self.page_4)
        self.verticalLayout_11.addWidget(self.stackedWidget)
        self.toolBox.addItem(self.page_6, _fromUtf8(""))
        self.page_7 = QtGui.QWidget()
        self.page_7.setObjectName(_fromUtf8("page_7"))
        self.tabWidget = QtGui.QTabWidget(self.page_7)
        self.tabWidget.setGeometry(QtCore.QRect(0, 10, 251, 128))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.tab)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.horizontalLayout_15 = QtGui.QHBoxLayout()
        self.horizontalLayout_15.setObjectName(_fromUtf8("horizontalLayout_15"))
        self.label_26 = QtGui.QLabel(self.tab)
        self.label_26.setMinimumSize(QtCore.QSize(98, 16))
        self.label_26.setMaximumSize(QtCore.QSize(98, 16))
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.horizontalLayout_15.addWidget(self.label_26)
        self.spinBox_13 = QtGui.QSpinBox(self.tab)
        self.spinBox_13.setMinimumSize(QtCore.QSize(69, 25))
        self.spinBox_13.setMaximumSize(QtCore.QSize(69, 25))
        self.spinBox_13.setMaximum(20000)
        self.spinBox_13.setProperty("value", 20000)
        self.spinBox_13.setObjectName(_fromUtf8("spinBox_13"))
        self.horizontalLayout_15.addWidget(self.spinBox_13)
        self.label_29 = QtGui.QLabel(self.tab)
        self.label_29.setMinimumSize(QtCore.QSize(17, 16))
        self.label_29.setMaximumSize(QtCore.QSize(17, 16))
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.horizontalLayout_15.addWidget(self.label_29)
        self.verticalLayout_8.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_16 = QtGui.QHBoxLayout()
        self.horizontalLayout_16.setObjectName(_fromUtf8("horizontalLayout_16"))
        self.label_30 = QtGui.QLabel(self.tab)
        self.label_30.setMinimumSize(QtCore.QSize(98, 16))
        self.label_30.setMaximumSize(QtCore.QSize(98, 16))
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.horizontalLayout_16.addWidget(self.label_30)
        self.spinBox_14 = QtGui.QSpinBox(self.tab)
        self.spinBox_14.setMinimumSize(QtCore.QSize(69, 25))
        self.spinBox_14.setMaximumSize(QtCore.QSize(69, 25))
        self.spinBox_14.setMaximum(20000)
        self.spinBox_14.setProperty("value", 20000)
        self.spinBox_14.setObjectName(_fromUtf8("spinBox_14"))
        self.horizontalLayout_16.addWidget(self.spinBox_14)
        self.label_31 = QtGui.QLabel(self.tab)
        self.label_31.setMinimumSize(QtCore.QSize(17, 16))
        self.label_31.setMaximumSize(QtCore.QSize(17, 16))
        self.label_31.setText(_fromUtf8(""))
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.horizontalLayout_16.addWidget(self.label_31)
        self.verticalLayout_8.addLayout(self.horizontalLayout_16)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.tab_2)
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.horizontalLayout_17 = QtGui.QHBoxLayout()
        self.horizontalLayout_17.setObjectName(_fromUtf8("horizontalLayout_17"))
        self.label_32 = QtGui.QLabel(self.tab_2)
        self.label_32.setMinimumSize(QtCore.QSize(98, 16))
        self.label_32.setMaximumSize(QtCore.QSize(98, 16))
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.horizontalLayout_17.addWidget(self.label_32)
        self.spinBox_15 = QtGui.QSpinBox(self.tab_2)
        self.spinBox_15.setMinimumSize(QtCore.QSize(69, 25))
        self.spinBox_15.setMaximumSize(QtCore.QSize(69, 25))
        self.spinBox_15.setMaximum(20000)
        self.spinBox_15.setProperty("value", 20000)
        self.spinBox_15.setObjectName(_fromUtf8("spinBox_15"))
        self.horizontalLayout_17.addWidget(self.spinBox_15)
        self.label_33 = QtGui.QLabel(self.tab_2)
        self.label_33.setMinimumSize(QtCore.QSize(17, 16))
        self.label_33.setMaximumSize(QtCore.QSize(17, 16))
        self.label_33.setObjectName(_fromUtf8("label_33"))
        self.horizontalLayout_17.addWidget(self.label_33)
        self.verticalLayout_9.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_18 = QtGui.QHBoxLayout()
        self.horizontalLayout_18.setObjectName(_fromUtf8("horizontalLayout_18"))
        self.label_34 = QtGui.QLabel(self.tab_2)
        self.label_34.setMinimumSize(QtCore.QSize(98, 16))
        self.label_34.setMaximumSize(QtCore.QSize(98, 16))
        self.label_34.setObjectName(_fromUtf8("label_34"))
        self.horizontalLayout_18.addWidget(self.label_34)
        self.spinBox_16 = QtGui.QSpinBox(self.tab_2)
        self.spinBox_16.setMinimumSize(QtCore.QSize(69, 25))
        self.spinBox_16.setMaximumSize(QtCore.QSize(69, 25))
        self.spinBox_16.setMaximum(20000)
        self.spinBox_16.setProperty("value", 20000)
        self.spinBox_16.setObjectName(_fromUtf8("spinBox_16"))
        self.horizontalLayout_18.addWidget(self.spinBox_16)
        self.label_35 = QtGui.QLabel(self.tab_2)
        self.label_35.setMinimumSize(QtCore.QSize(17, 16))
        self.label_35.setMaximumSize(QtCore.QSize(17, 16))
        self.label_35.setText(_fromUtf8(""))
        self.label_35.setObjectName(_fromUtf8("label_35"))
        self.horizontalLayout_18.addWidget(self.label_35)
        self.verticalLayout_9.addLayout(self.horizontalLayout_18)
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.toolBox.addItem(self.page_7, _fromUtf8(""))
        self.page_8 = QtGui.QWidget()
        self.page_8.setObjectName(_fromUtf8("page_8"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.page_8)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.horizontalLayout_21 = QtGui.QHBoxLayout()
        self.horizontalLayout_21.setObjectName(_fromUtf8("horizontalLayout_21"))
        self.label_36 = QtGui.QLabel(self.page_8)
        self.label_36.setObjectName(_fromUtf8("label_36"))
        self.horizontalLayout_21.addWidget(self.label_36)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_21.addItem(spacerItem1)
        self.verticalLayout_5.addLayout(self.horizontalLayout_21)
        self.lineEdit_2 = QtGui.QLineEdit(self.page_8)
        self.lineEdit_2.setObjectName(_fromUtf8("lineEdit_2"))
        self.verticalLayout_5.addWidget(self.lineEdit_2)
        self.horizontalLayout_19 = QtGui.QHBoxLayout()
        self.horizontalLayout_19.setObjectName(_fromUtf8("horizontalLayout_19"))
        self.label = QtGui.QLabel(self.page_8)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_19.addWidget(self.label)
        self.pushButton = QtGui.QPushButton(self.page_8)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.horizontalLayout_19.addWidget(self.pushButton)
        self.verticalLayout_5.addLayout(self.horizontalLayout_19)
        self.lineEdit = QtGui.QLineEdit(self.page_8)
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.verticalLayout_5.addWidget(self.lineEdit)
        self.horizontalLayout_22 = QtGui.QHBoxLayout()
        self.horizontalLayout_22.setObjectName(_fromUtf8("horizontalLayout_22"))
        self.label_38 = QtGui.QLabel(self.page_8)
        self.label_38.setObjectName(_fromUtf8("label_38"))
        self.horizontalLayout_22.addWidget(self.label_38)
        self.spinBox_17 = QtGui.QSpinBox(self.page_8)
        self.spinBox_17.setObjectName(_fromUtf8("spinBox_17"))
        self.horizontalLayout_22.addWidget(self.spinBox_17)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_22.addItem(spacerItem2)
        self.verticalLayout_5.addLayout(self.horizontalLayout_22)
        self.toolBox.addItem(self.page_8, _fromUtf8(""))
        self.verticalLayout_6.addWidget(self.toolBox)
        self.horizontalLayout_23 = QtGui.QHBoxLayout()
        self.horizontalLayout_23.setObjectName(_fromUtf8("horizontalLayout_23"))
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_23.addItem(spacerItem3)
        self.pushButton_2 = QtGui.QPushButton(self.frame)
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.horizontalLayout_23.addWidget(self.pushButton_2)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_23.addItem(spacerItem4)
        self.verticalLayout_6.addLayout(self.horizontalLayout_23)
        self.verticalLayout_22.addWidget(self.frame)
        self.horizontalLayout_53.addLayout(self.verticalLayout_22)
        self.verticalLayout_23 = QtGui.QVBoxLayout()
        self.verticalLayout_23.setObjectName(_fromUtf8("verticalLayout_23"))
        self.horizontalLayout_52 = QtGui.QHBoxLayout()
        self.horizontalLayout_52.setObjectName(_fromUtf8("horizontalLayout_52"))
        self.label_82 = QtGui.QLabel(self.centralwidget)
        self.label_82.setObjectName(_fromUtf8("label_82"))
        self.horizontalLayout_52.addWidget(self.label_82)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_52.addItem(spacerItem5)
        self.verticalLayout_23.addLayout(self.horizontalLayout_52)
        self.frame_2 = QtGui.QFrame(self.centralwidget)
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.frame_2)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.horizontalLayout_24 = QtGui.QHBoxLayout()
        self.horizontalLayout_24.setObjectName(_fromUtf8("horizontalLayout_24"))
        self.label_40 = QtGui.QLabel(self.frame_2)
        self.label_40.setObjectName(_fromUtf8("label_40"))
        self.horizontalLayout_24.addWidget(self.label_40)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_24.addItem(spacerItem6)
        self.verticalLayout_7.addLayout(self.horizontalLayout_24)
        self.mplwidget = MatplotlibWidget(self.frame_2)
        self.mplwidget.setObjectName(_fromUtf8("mplwidget"))
        self.verticalLayout_7.addWidget(self.mplwidget)
        self.horizontalLayout_25 = QtGui.QHBoxLayout()
        self.horizontalLayout_25.setObjectName(_fromUtf8("horizontalLayout_25"))
        self.label_41 = QtGui.QLabel(self.frame_2)
        self.label_41.setObjectName(_fromUtf8("label_41"))
        self.horizontalLayout_25.addWidget(self.label_41)
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_25.addItem(spacerItem7)
        self.verticalLayout_7.addLayout(self.horizontalLayout_25)
        self.mplwidget_2 = MatplotlibWidget(self.frame_2)
        self.mplwidget_2.setObjectName(_fromUtf8("mplwidget_2"))
        self.verticalLayout_7.addWidget(self.mplwidget_2)
        self.horizontalLayout_26 = QtGui.QHBoxLayout()
        self.horizontalLayout_26.setObjectName(_fromUtf8("horizontalLayout_26"))
        self.label_42 = QtGui.QLabel(self.frame_2)
        self.label_42.setObjectName(_fromUtf8("label_42"))
        self.horizontalLayout_26.addWidget(self.label_42)
        spacerItem8 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_26.addItem(spacerItem8)
        self.verticalLayout_7.addLayout(self.horizontalLayout_26)
        self.mplwidget_3 = MatplotlibWidget(self.frame_2)
        self.mplwidget_3.setObjectName(_fromUtf8("mplwidget_3"))
        self.verticalLayout_7.addWidget(self.mplwidget_3)
        self.verticalLayout_23.addWidget(self.frame_2)
        self.horizontalLayout_53.addLayout(self.verticalLayout_23)
        self.verticalLayout_24 = QtGui.QVBoxLayout()
        self.verticalLayout_24.setObjectName(_fromUtf8("verticalLayout_24"))
        self.horizontalLayout_51 = QtGui.QHBoxLayout()
        self.horizontalLayout_51.setObjectName(_fromUtf8("horizontalLayout_51"))
        self.label_81 = QtGui.QLabel(self.centralwidget)
        self.label_81.setObjectName(_fromUtf8("label_81"))
        self.horizontalLayout_51.addWidget(self.label_81)
        spacerItem9 = QtGui.QSpacerItem(138, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_51.addItem(spacerItem9)
        self.verticalLayout_24.addLayout(self.horizontalLayout_51)
        self.frame_3 = QtGui.QFrame(self.centralwidget)
        self.frame_3.setMaximumSize(QtCore.QSize(320, 692))
        self.frame_3.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_3.setObjectName(_fromUtf8("frame_3"))
        self.verticalLayout_10 = QtGui.QVBoxLayout(self.frame_3)
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.toolBox_2 = QtGui.QToolBox(self.frame_3)
        self.toolBox_2.setObjectName(_fromUtf8("toolBox_2"))
        self.page_9 = QtGui.QWidget()
        self.page_9.setGeometry(QtCore.QRect(0, 0, 294, 488))
        self.page_9.setObjectName(_fromUtf8("page_9"))
        self.verticalLayout_13 = QtGui.QVBoxLayout(self.page_9)
        self.verticalLayout_13.setObjectName(_fromUtf8("verticalLayout_13"))
        self.horizontalLayout_27 = QtGui.QHBoxLayout()
        self.horizontalLayout_27.setObjectName(_fromUtf8("horizontalLayout_27"))
        self.label_43 = QtGui.QLabel(self.page_9)
        self.label_43.setMinimumSize(QtCore.QSize(91, 16))
        self.label_43.setMaximumSize(QtCore.QSize(91, 16))
        self.label_43.setObjectName(_fromUtf8("label_43"))
        self.horizontalLayout_27.addWidget(self.label_43)
        self.comboBox_4 = QtGui.QComboBox(self.page_9)
        self.comboBox_4.setMinimumSize(QtCore.QSize(131, 26))
        self.comboBox_4.setMaximumSize(QtCore.QSize(131, 26))
        self.comboBox_4.setObjectName(_fromUtf8("comboBox_4"))
        self.horizontalLayout_27.addWidget(self.comboBox_4)
        self.verticalLayout_13.addLayout(self.horizontalLayout_27)
        self.horizontalLayout_28 = QtGui.QHBoxLayout()
        self.horizontalLayout_28.setObjectName(_fromUtf8("horizontalLayout_28"))
        self.label_44 = QtGui.QLabel(self.page_9)
        self.label_44.setMinimumSize(QtCore.QSize(91, 16))
        self.label_44.setMaximumSize(QtCore.QSize(91, 16))
        self.label_44.setObjectName(_fromUtf8("label_44"))
        self.horizontalLayout_28.addWidget(self.label_44)
        self.comboBox_5 = QtGui.QComboBox(self.page_9)
        self.comboBox_5.setMinimumSize(QtCore.QSize(131, 26))
        self.comboBox_5.setMaximumSize(QtCore.QSize(131, 26))
        self.comboBox_5.setObjectName(_fromUtf8("comboBox_5"))
        self.horizontalLayout_28.addWidget(self.comboBox_5)
        self.verticalLayout_13.addLayout(self.horizontalLayout_28)
        self.horizontalLayout_29 = QtGui.QHBoxLayout()
        self.horizontalLayout_29.setObjectName(_fromUtf8("horizontalLayout_29"))
        self.label_45 = QtGui.QLabel(self.page_9)
        self.label_45.setMinimumSize(QtCore.QSize(91, 16))
        self.label_45.setMaximumSize(QtCore.QSize(91, 16))
        self.label_45.setObjectName(_fromUtf8("label_45"))
        self.horizontalLayout_29.addWidget(self.label_45)
        self.horizontalSlider_2 = QtGui.QSlider(self.page_9)
        self.horizontalSlider_2.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_2.setObjectName(_fromUtf8("horizontalSlider_2"))
        self.horizontalLayout_29.addWidget(self.horizontalSlider_2)
        self.doubleSpinBox_2 = QtGui.QDoubleSpinBox(self.page_9)
        self.doubleSpinBox_2.setEnabled(False)
        self.doubleSpinBox_2.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.doubleSpinBox_2.setMaximum(1.0)
        self.doubleSpinBox_2.setSingleStep(0.1)
        self.doubleSpinBox_2.setObjectName(_fromUtf8("doubleSpinBox_2"))
        self.horizontalLayout_29.addWidget(self.doubleSpinBox_2)
        self.verticalLayout_13.addLayout(self.horizontalLayout_29)
        self.toolBox_2.addItem(self.page_9, _fromUtf8(""))
        self.page_10 = QtGui.QWidget()
        self.page_10.setGeometry(QtCore.QRect(0, 0, 294, 488))
        self.page_10.setObjectName(_fromUtf8("page_10"))
        self.verticalLayout_14 = QtGui.QVBoxLayout(self.page_10)
        self.verticalLayout_14.setObjectName(_fromUtf8("verticalLayout_14"))
        self.comboBox_6 = QtGui.QComboBox(self.page_10)
        self.comboBox_6.setObjectName(_fromUtf8("comboBox_6"))
        self.comboBox_6.addItem(_fromUtf8(""))
        self.comboBox_6.addItem(_fromUtf8(""))
        self.comboBox_6.addItem(_fromUtf8(""))
        self.comboBox_6.addItem(_fromUtf8(""))
        self.verticalLayout_14.addWidget(self.comboBox_6)
        self.stackedWidget_2 = QtGui.QStackedWidget(self.page_10)
        self.stackedWidget_2.setObjectName(_fromUtf8("stackedWidget_2"))
        self.page_11 = QtGui.QWidget()
        self.page_11.setObjectName(_fromUtf8("page_11"))
        self.verticalLayout_15 = QtGui.QVBoxLayout(self.page_11)
        self.verticalLayout_15.setObjectName(_fromUtf8("verticalLayout_15"))
        self.horizontalLayout_30 = QtGui.QHBoxLayout()
        self.horizontalLayout_30.setObjectName(_fromUtf8("horizontalLayout_30"))
        self.label_46 = QtGui.QLabel(self.page_11)
        self.label_46.setMinimumSize(QtCore.QSize(98, 16))
        self.label_46.setMaximumSize(QtCore.QSize(98, 16))
        self.label_46.setObjectName(_fromUtf8("label_46"))
        self.horizontalLayout_30.addWidget(self.label_46)
        self.spinBox_18 = QtGui.QSpinBox(self.page_11)
        self.spinBox_18.setMaximum(20000)
        self.spinBox_18.setProperty("value", 20000)
        self.spinBox_18.setObjectName(_fromUtf8("spinBox_18"))
        self.horizontalLayout_30.addWidget(self.spinBox_18)
        self.label_47 = QtGui.QLabel(self.page_11)
        self.label_47.setObjectName(_fromUtf8("label_47"))
        self.horizontalLayout_30.addWidget(self.label_47)
        self.verticalLayout_15.addLayout(self.horizontalLayout_30)
        self.horizontalLayout_31 = QtGui.QHBoxLayout()
        self.horizontalLayout_31.setObjectName(_fromUtf8("horizontalLayout_31"))
        self.label_48 = QtGui.QLabel(self.page_11)
        self.label_48.setMinimumSize(QtCore.QSize(98, 16))
        self.label_48.setMaximumSize(QtCore.QSize(98, 16))
        self.label_48.setObjectName(_fromUtf8("label_48"))
        self.horizontalLayout_31.addWidget(self.label_48)
        self.spinBox_19 = QtGui.QSpinBox(self.page_11)
        self.spinBox_19.setMaximum(20000)
        self.spinBox_19.setProperty("value", 20000)
        self.spinBox_19.setObjectName(_fromUtf8("spinBox_19"))
        self.horizontalLayout_31.addWidget(self.spinBox_19)
        self.label_49 = QtGui.QLabel(self.page_11)
        self.label_49.setObjectName(_fromUtf8("label_49"))
        self.horizontalLayout_31.addWidget(self.label_49)
        self.verticalLayout_15.addLayout(self.horizontalLayout_31)
        self.horizontalLayout_32 = QtGui.QHBoxLayout()
        self.horizontalLayout_32.setObjectName(_fromUtf8("horizontalLayout_32"))
        self.label_50 = QtGui.QLabel(self.page_11)
        self.label_50.setMinimumSize(QtCore.QSize(98, 16))
        self.label_50.setMaximumSize(QtCore.QSize(98, 16))
        self.label_50.setObjectName(_fromUtf8("label_50"))
        self.horizontalLayout_32.addWidget(self.label_50)
        self.spinBox_20 = QtGui.QSpinBox(self.page_11)
        self.spinBox_20.setMaximum(20000)
        self.spinBox_20.setProperty("value", 20000)
        self.spinBox_20.setObjectName(_fromUtf8("spinBox_20"))
        self.horizontalLayout_32.addWidget(self.spinBox_20)
        self.label_51 = QtGui.QLabel(self.page_11)
        self.label_51.setObjectName(_fromUtf8("label_51"))
        self.horizontalLayout_32.addWidget(self.label_51)
        self.verticalLayout_15.addLayout(self.horizontalLayout_32)
        self.stackedWidget_2.addWidget(self.page_11)
        self.page_12 = QtGui.QWidget()
        self.page_12.setObjectName(_fromUtf8("page_12"))
        self.verticalLayout_16 = QtGui.QVBoxLayout(self.page_12)
        self.verticalLayout_16.setObjectName(_fromUtf8("verticalLayout_16"))
        self.horizontalLayout_33 = QtGui.QHBoxLayout()
        self.horizontalLayout_33.setObjectName(_fromUtf8("horizontalLayout_33"))
        self.label_52 = QtGui.QLabel(self.page_12)
        self.label_52.setMinimumSize(QtCore.QSize(98, 16))
        self.label_52.setMaximumSize(QtCore.QSize(98, 16))
        self.label_52.setObjectName(_fromUtf8("label_52"))
        self.horizontalLayout_33.addWidget(self.label_52)
        self.spinBox_21 = QtGui.QSpinBox(self.page_12)
        self.spinBox_21.setMinimumSize(QtCore.QSize(69, 25))
        self.spinBox_21.setMaximumSize(QtCore.QSize(69, 25))
        self.spinBox_21.setMaximum(20000)
        self.spinBox_21.setProperty("value", 20000)
        self.spinBox_21.setObjectName(_fromUtf8("spinBox_21"))
        self.horizontalLayout_33.addWidget(self.spinBox_21)
        self.label_53 = QtGui.QLabel(self.page_12)
        self.label_53.setMinimumSize(QtCore.QSize(17, 16))
        self.label_53.setMaximumSize(QtCore.QSize(17, 16))
        self.label_53.setObjectName(_fromUtf8("label_53"))
        self.horizontalLayout_33.addWidget(self.label_53)
        self.verticalLayout_16.addLayout(self.horizontalLayout_33)
        self.horizontalLayout_34 = QtGui.QHBoxLayout()
        self.horizontalLayout_34.setObjectName(_fromUtf8("horizontalLayout_34"))
        self.label_54 = QtGui.QLabel(self.page_12)
        self.label_54.setMinimumSize(QtCore.QSize(98, 16))
        self.label_54.setMaximumSize(QtCore.QSize(98, 16))
        self.label_54.setObjectName(_fromUtf8("label_54"))
        self.horizontalLayout_34.addWidget(self.label_54)
        self.spinBox_22 = QtGui.QSpinBox(self.page_12)
        self.spinBox_22.setMinimumSize(QtCore.QSize(69, 25))
        self.spinBox_22.setMaximumSize(QtCore.QSize(69, 25))
        self.spinBox_22.setMaximum(20000)
        self.spinBox_22.setProperty("value", 20000)
        self.spinBox_22.setObjectName(_fromUtf8("spinBox_22"))
        self.horizontalLayout_34.addWidget(self.spinBox_22)
        self.label_55 = QtGui.QLabel(self.page_12)
        self.label_55.setMinimumSize(QtCore.QSize(17, 16))
        self.label_55.setMaximumSize(QtCore.QSize(17, 16))
        self.label_55.setObjectName(_fromUtf8("label_55"))
        self.horizontalLayout_34.addWidget(self.label_55)
        self.verticalLayout_16.addLayout(self.horizontalLayout_34)
        self.horizontalLayout_35 = QtGui.QHBoxLayout()
        self.horizontalLayout_35.setObjectName(_fromUtf8("horizontalLayout_35"))
        self.label_56 = QtGui.QLabel(self.page_12)
        self.label_56.setMinimumSize(QtCore.QSize(98, 16))
        self.label_56.setMaximumSize(QtCore.QSize(98, 16))
        self.label_56.setObjectName(_fromUtf8("label_56"))
        self.horizontalLayout_35.addWidget(self.label_56)
        self.spinBox_23 = QtGui.QSpinBox(self.page_12)
        self.spinBox_23.setMinimumSize(QtCore.QSize(69, 25))
        self.spinBox_23.setMaximumSize(QtCore.QSize(69, 25))
        self.spinBox_23.setMaximum(20000)
        self.spinBox_23.setProperty("value", 20000)
        self.spinBox_23.setObjectName(_fromUtf8("spinBox_23"))
        self.horizontalLayout_35.addWidget(self.spinBox_23)
        self.label_57 = QtGui.QLabel(self.page_12)
        self.label_57.setMinimumSize(QtCore.QSize(17, 16))
        self.label_57.setMaximumSize(QtCore.QSize(17, 16))
        self.label_57.setText(_fromUtf8(""))
        self.label_57.setObjectName(_fromUtf8("label_57"))
        self.horizontalLayout_35.addWidget(self.label_57)
        self.verticalLayout_16.addLayout(self.horizontalLayout_35)
        self.stackedWidget_2.addWidget(self.page_12)
        self.page_13 = QtGui.QWidget()
        self.page_13.setObjectName(_fromUtf8("page_13"))
        self.verticalLayout_17 = QtGui.QVBoxLayout(self.page_13)
        self.verticalLayout_17.setObjectName(_fromUtf8("verticalLayout_17"))
        self.horizontalLayout_36 = QtGui.QHBoxLayout()
        self.horizontalLayout_36.setObjectName(_fromUtf8("horizontalLayout_36"))
        self.label_58 = QtGui.QLabel(self.page_13)
        self.label_58.setMinimumSize(QtCore.QSize(98, 16))
        self.label_58.setMaximumSize(QtCore.QSize(98, 16))
        self.label_58.setObjectName(_fromUtf8("label_58"))
        self.horizontalLayout_36.addWidget(self.label_58)
        self.spinBox_24 = QtGui.QSpinBox(self.page_13)
        self.spinBox_24.setMinimumSize(QtCore.QSize(69, 25))
        self.spinBox_24.setMaximumSize(QtCore.QSize(69, 25))
        self.spinBox_24.setMinimum(3)
        self.spinBox_24.setMaximum(18)
        self.spinBox_24.setProperty("value", 18)
        self.spinBox_24.setObjectName(_fromUtf8("spinBox_24"))
        self.horizontalLayout_36.addWidget(self.spinBox_24)
        self.label_59 = QtGui.QLabel(self.page_13)
        self.label_59.setMinimumSize(QtCore.QSize(17, 16))
        self.label_59.setMaximumSize(QtCore.QSize(17, 16))
        self.label_59.setText(_fromUtf8(""))
        self.label_59.setObjectName(_fromUtf8("label_59"))
        self.horizontalLayout_36.addWidget(self.label_59)
        self.verticalLayout_17.addLayout(self.horizontalLayout_36)
        self.horizontalLayout_37 = QtGui.QHBoxLayout()
        self.horizontalLayout_37.setObjectName(_fromUtf8("horizontalLayout_37"))
        self.label_60 = QtGui.QLabel(self.page_13)
        self.label_60.setMinimumSize(QtCore.QSize(98, 16))
        self.label_60.setMaximumSize(QtCore.QSize(98, 16))
        self.label_60.setObjectName(_fromUtf8("label_60"))
        self.horizontalLayout_37.addWidget(self.label_60)
        self.spinBox_25 = QtGui.QSpinBox(self.page_13)
        self.spinBox_25.setMinimumSize(QtCore.QSize(69, 25))
        self.spinBox_25.setMaximumSize(QtCore.QSize(69, 25))
        self.spinBox_25.setMinimum(3)
        self.spinBox_25.setMaximum(18)
        self.spinBox_25.setProperty("value", 18)
        self.spinBox_25.setObjectName(_fromUtf8("spinBox_25"))
        self.horizontalLayout_37.addWidget(self.spinBox_25)
        self.label_61 = QtGui.QLabel(self.page_13)
        self.label_61.setMinimumSize(QtCore.QSize(17, 16))
        self.label_61.setMaximumSize(QtCore.QSize(17, 16))
        self.label_61.setText(_fromUtf8(""))
        self.label_61.setObjectName(_fromUtf8("label_61"))
        self.horizontalLayout_37.addWidget(self.label_61)
        self.verticalLayout_17.addLayout(self.horizontalLayout_37)
        self.horizontalLayout_38 = QtGui.QHBoxLayout()
        self.horizontalLayout_38.setObjectName(_fromUtf8("horizontalLayout_38"))
        self.label_62 = QtGui.QLabel(self.page_13)
        self.label_62.setMinimumSize(QtCore.QSize(98, 16))
        self.label_62.setMaximumSize(QtCore.QSize(98, 16))
        self.label_62.setObjectName(_fromUtf8("label_62"))
        self.horizontalLayout_38.addWidget(self.label_62)
        self.spinBox_26 = QtGui.QSpinBox(self.page_13)
        self.spinBox_26.setEnabled(False)
        self.spinBox_26.setMinimumSize(QtCore.QSize(69, 25))
        self.spinBox_26.setMaximumSize(QtCore.QSize(69, 25))
        self.spinBox_26.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.spinBox_26.setMinimum(3)
        self.spinBox_26.setMaximum(18)
        self.spinBox_26.setProperty("value", 18)
        self.spinBox_26.setObjectName(_fromUtf8("spinBox_26"))
        self.horizontalLayout_38.addWidget(self.spinBox_26)
        self.label_63 = QtGui.QLabel(self.page_13)
        self.label_63.setMinimumSize(QtCore.QSize(17, 16))
        self.label_63.setMaximumSize(QtCore.QSize(17, 16))
        self.label_63.setObjectName(_fromUtf8("label_63"))
        self.horizontalLayout_38.addWidget(self.label_63)
        self.verticalLayout_17.addLayout(self.horizontalLayout_38)
        self.stackedWidget_2.addWidget(self.page_13)
        self.page_14 = QtGui.QWidget()
        self.page_14.setObjectName(_fromUtf8("page_14"))
        self.verticalLayout_18 = QtGui.QVBoxLayout(self.page_14)
        self.verticalLayout_18.setObjectName(_fromUtf8("verticalLayout_18"))
        self.horizontalLayout_39 = QtGui.QHBoxLayout()
        self.horizontalLayout_39.setObjectName(_fromUtf8("horizontalLayout_39"))
        self.label_64 = QtGui.QLabel(self.page_14)
        self.label_64.setMinimumSize(QtCore.QSize(98, 16))
        self.label_64.setMaximumSize(QtCore.QSize(98, 16))
        self.label_64.setObjectName(_fromUtf8("label_64"))
        self.horizontalLayout_39.addWidget(self.label_64)
        self.spinBox_27 = QtGui.QSpinBox(self.page_14)
        self.spinBox_27.setMinimumSize(QtCore.QSize(69, 25))
        self.spinBox_27.setMaximumSize(QtCore.QSize(69, 25))
        self.spinBox_27.setMinimum(3)
        self.spinBox_27.setMaximum(18)
        self.spinBox_27.setProperty("value", 18)
        self.spinBox_27.setObjectName(_fromUtf8("spinBox_27"))
        self.horizontalLayout_39.addWidget(self.spinBox_27)
        self.label_65 = QtGui.QLabel(self.page_14)
        self.label_65.setMinimumSize(QtCore.QSize(17, 16))
        self.label_65.setMaximumSize(QtCore.QSize(17, 16))
        self.label_65.setText(_fromUtf8(""))
        self.label_65.setObjectName(_fromUtf8("label_65"))
        self.horizontalLayout_39.addWidget(self.label_65)
        self.verticalLayout_18.addLayout(self.horizontalLayout_39)
        self.horizontalLayout_40 = QtGui.QHBoxLayout()
        self.horizontalLayout_40.setObjectName(_fromUtf8("horizontalLayout_40"))
        self.label_66 = QtGui.QLabel(self.page_14)
        self.label_66.setMinimumSize(QtCore.QSize(98, 16))
        self.label_66.setMaximumSize(QtCore.QSize(98, 16))
        self.label_66.setObjectName(_fromUtf8("label_66"))
        self.horizontalLayout_40.addWidget(self.label_66)
        self.spinBox_28 = QtGui.QSpinBox(self.page_14)
        self.spinBox_28.setMinimumSize(QtCore.QSize(69, 25))
        self.spinBox_28.setMaximumSize(QtCore.QSize(69, 25))
        self.spinBox_28.setMinimum(3)
        self.spinBox_28.setMaximum(18)
        self.spinBox_28.setProperty("value", 18)
        self.spinBox_28.setObjectName(_fromUtf8("spinBox_28"))
        self.horizontalLayout_40.addWidget(self.spinBox_28)
        self.label_67 = QtGui.QLabel(self.page_14)
        self.label_67.setMinimumSize(QtCore.QSize(17, 16))
        self.label_67.setMaximumSize(QtCore.QSize(17, 16))
        self.label_67.setText(_fromUtf8(""))
        self.label_67.setObjectName(_fromUtf8("label_67"))
        self.horizontalLayout_40.addWidget(self.label_67)
        self.verticalLayout_18.addLayout(self.horizontalLayout_40)
        self.horizontalLayout_41 = QtGui.QHBoxLayout()
        self.horizontalLayout_41.setObjectName(_fromUtf8("horizontalLayout_41"))
        self.label_68 = QtGui.QLabel(self.page_14)
        self.label_68.setMinimumSize(QtCore.QSize(98, 16))
        self.label_68.setMaximumSize(QtCore.QSize(98, 16))
        self.label_68.setObjectName(_fromUtf8("label_68"))
        self.horizontalLayout_41.addWidget(self.label_68)
        self.spinBox_29 = QtGui.QSpinBox(self.page_14)
        self.spinBox_29.setEnabled(False)
        self.spinBox_29.setMinimumSize(QtCore.QSize(69, 25))
        self.spinBox_29.setMaximumSize(QtCore.QSize(69, 25))
        self.spinBox_29.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.spinBox_29.setMinimum(3)
        self.spinBox_29.setMaximum(18)
        self.spinBox_29.setProperty("value", 18)
        self.spinBox_29.setObjectName(_fromUtf8("spinBox_29"))
        self.horizontalLayout_41.addWidget(self.spinBox_29)
        self.label_69 = QtGui.QLabel(self.page_14)
        self.label_69.setMinimumSize(QtCore.QSize(17, 16))
        self.label_69.setMaximumSize(QtCore.QSize(17, 16))
        self.label_69.setObjectName(_fromUtf8("label_69"))
        self.horizontalLayout_41.addWidget(self.label_69)
        self.verticalLayout_18.addLayout(self.horizontalLayout_41)
        self.stackedWidget_2.addWidget(self.page_14)
        self.verticalLayout_14.addWidget(self.stackedWidget_2)
        self.toolBox_2.addItem(self.page_10, _fromUtf8(""))
        self.page_15 = QtGui.QWidget()
        self.page_15.setGeometry(QtCore.QRect(0, 0, 294, 488))
        self.page_15.setObjectName(_fromUtf8("page_15"))
        self.tabWidget_2 = QtGui.QTabWidget(self.page_15)
        self.tabWidget_2.setGeometry(QtCore.QRect(0, 10, 251, 128))
        self.tabWidget_2.setObjectName(_fromUtf8("tabWidget_2"))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.verticalLayout_19 = QtGui.QVBoxLayout(self.tab_3)
        self.verticalLayout_19.setObjectName(_fromUtf8("verticalLayout_19"))
        self.horizontalLayout_42 = QtGui.QHBoxLayout()
        self.horizontalLayout_42.setObjectName(_fromUtf8("horizontalLayout_42"))
        self.label_70 = QtGui.QLabel(self.tab_3)
        self.label_70.setMinimumSize(QtCore.QSize(98, 16))
        self.label_70.setMaximumSize(QtCore.QSize(98, 16))
        self.label_70.setObjectName(_fromUtf8("label_70"))
        self.horizontalLayout_42.addWidget(self.label_70)
        self.spinBox_30 = QtGui.QSpinBox(self.tab_3)
        self.spinBox_30.setMinimumSize(QtCore.QSize(69, 25))
        self.spinBox_30.setMaximumSize(QtCore.QSize(69, 25))
        self.spinBox_30.setMaximum(20000)
        self.spinBox_30.setProperty("value", 20000)
        self.spinBox_30.setObjectName(_fromUtf8("spinBox_30"))
        self.horizontalLayout_42.addWidget(self.spinBox_30)
        self.label_71 = QtGui.QLabel(self.tab_3)
        self.label_71.setMinimumSize(QtCore.QSize(17, 16))
        self.label_71.setMaximumSize(QtCore.QSize(17, 16))
        self.label_71.setObjectName(_fromUtf8("label_71"))
        self.horizontalLayout_42.addWidget(self.label_71)
        self.verticalLayout_19.addLayout(self.horizontalLayout_42)
        self.horizontalLayout_43 = QtGui.QHBoxLayout()
        self.horizontalLayout_43.setObjectName(_fromUtf8("horizontalLayout_43"))
        self.label_72 = QtGui.QLabel(self.tab_3)
        self.label_72.setMinimumSize(QtCore.QSize(98, 16))
        self.label_72.setMaximumSize(QtCore.QSize(98, 16))
        self.label_72.setObjectName(_fromUtf8("label_72"))
        self.horizontalLayout_43.addWidget(self.label_72)
        self.spinBox_31 = QtGui.QSpinBox(self.tab_3)
        self.spinBox_31.setMinimumSize(QtCore.QSize(69, 25))
        self.spinBox_31.setMaximumSize(QtCore.QSize(69, 25))
        self.spinBox_31.setMaximum(20000)
        self.spinBox_31.setProperty("value", 20000)
        self.spinBox_31.setObjectName(_fromUtf8("spinBox_31"))
        self.horizontalLayout_43.addWidget(self.spinBox_31)
        self.label_73 = QtGui.QLabel(self.tab_3)
        self.label_73.setMinimumSize(QtCore.QSize(17, 16))
        self.label_73.setMaximumSize(QtCore.QSize(17, 16))
        self.label_73.setText(_fromUtf8(""))
        self.label_73.setObjectName(_fromUtf8("label_73"))
        self.horizontalLayout_43.addWidget(self.label_73)
        self.verticalLayout_19.addLayout(self.horizontalLayout_43)
        self.tabWidget_2.addTab(self.tab_3, _fromUtf8(""))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.verticalLayout_20 = QtGui.QVBoxLayout(self.tab_4)
        self.verticalLayout_20.setObjectName(_fromUtf8("verticalLayout_20"))
        self.horizontalLayout_44 = QtGui.QHBoxLayout()
        self.horizontalLayout_44.setObjectName(_fromUtf8("horizontalLayout_44"))
        self.label_74 = QtGui.QLabel(self.tab_4)
        self.label_74.setMinimumSize(QtCore.QSize(98, 16))
        self.label_74.setMaximumSize(QtCore.QSize(98, 16))
        self.label_74.setObjectName(_fromUtf8("label_74"))
        self.horizontalLayout_44.addWidget(self.label_74)
        self.spinBox_32 = QtGui.QSpinBox(self.tab_4)
        self.spinBox_32.setMinimumSize(QtCore.QSize(69, 25))
        self.spinBox_32.setMaximumSize(QtCore.QSize(69, 25))
        self.spinBox_32.setMaximum(20000)
        self.spinBox_32.setProperty("value", 20000)
        self.spinBox_32.setObjectName(_fromUtf8("spinBox_32"))
        self.horizontalLayout_44.addWidget(self.spinBox_32)
        self.label_75 = QtGui.QLabel(self.tab_4)
        self.label_75.setMinimumSize(QtCore.QSize(17, 16))
        self.label_75.setMaximumSize(QtCore.QSize(17, 16))
        self.label_75.setObjectName(_fromUtf8("label_75"))
        self.horizontalLayout_44.addWidget(self.label_75)
        self.verticalLayout_20.addLayout(self.horizontalLayout_44)
        self.horizontalLayout_45 = QtGui.QHBoxLayout()
        self.horizontalLayout_45.setObjectName(_fromUtf8("horizontalLayout_45"))
        self.label_76 = QtGui.QLabel(self.tab_4)
        self.label_76.setMinimumSize(QtCore.QSize(98, 16))
        self.label_76.setMaximumSize(QtCore.QSize(98, 16))
        self.label_76.setObjectName(_fromUtf8("label_76"))
        self.horizontalLayout_45.addWidget(self.label_76)
        self.spinBox_33 = QtGui.QSpinBox(self.tab_4)
        self.spinBox_33.setMinimumSize(QtCore.QSize(69, 25))
        self.spinBox_33.setMaximumSize(QtCore.QSize(69, 25))
        self.spinBox_33.setMaximum(20000)
        self.spinBox_33.setProperty("value", 20000)
        self.spinBox_33.setObjectName(_fromUtf8("spinBox_33"))
        self.horizontalLayout_45.addWidget(self.spinBox_33)
        self.label_77 = QtGui.QLabel(self.tab_4)
        self.label_77.setMinimumSize(QtCore.QSize(17, 16))
        self.label_77.setMaximumSize(QtCore.QSize(17, 16))
        self.label_77.setText(_fromUtf8(""))
        self.label_77.setObjectName(_fromUtf8("label_77"))
        self.horizontalLayout_45.addWidget(self.label_77)
        self.verticalLayout_20.addLayout(self.horizontalLayout_45)
        self.tabWidget_2.addTab(self.tab_4, _fromUtf8(""))
        self.toolBox_2.addItem(self.page_15, _fromUtf8(""))
        self.page_16 = QtGui.QWidget()
        self.page_16.setGeometry(QtCore.QRect(0, 0, 294, 488))
        self.page_16.setObjectName(_fromUtf8("page_16"))
        self.verticalLayout_21 = QtGui.QVBoxLayout(self.page_16)
        self.verticalLayout_21.setObjectName(_fromUtf8("verticalLayout_21"))
        self.horizontalLayout_46 = QtGui.QHBoxLayout()
        self.horizontalLayout_46.setObjectName(_fromUtf8("horizontalLayout_46"))
        self.label_78 = QtGui.QLabel(self.page_16)
        self.label_78.setObjectName(_fromUtf8("label_78"))
        self.horizontalLayout_46.addWidget(self.label_78)
        spacerItem10 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_46.addItem(spacerItem10)
        self.verticalLayout_21.addLayout(self.horizontalLayout_46)
        self.lineEdit_3 = QtGui.QLineEdit(self.page_16)
        self.lineEdit_3.setObjectName(_fromUtf8("lineEdit_3"))
        self.verticalLayout_21.addWidget(self.lineEdit_3)
        self.horizontalLayout_47 = QtGui.QHBoxLayout()
        self.horizontalLayout_47.setObjectName(_fromUtf8("horizontalLayout_47"))
        self.label_79 = QtGui.QLabel(self.page_16)
        self.label_79.setObjectName(_fromUtf8("label_79"))
        self.horizontalLayout_47.addWidget(self.label_79)
        self.pushButton_3 = QtGui.QPushButton(self.page_16)
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.horizontalLayout_47.addWidget(self.pushButton_3)
        self.verticalLayout_21.addLayout(self.horizontalLayout_47)
        self.lineEdit_4 = QtGui.QLineEdit(self.page_16)
        self.lineEdit_4.setObjectName(_fromUtf8("lineEdit_4"))
        self.verticalLayout_21.addWidget(self.lineEdit_4)
        self.horizontalLayout_48 = QtGui.QHBoxLayout()
        self.horizontalLayout_48.setObjectName(_fromUtf8("horizontalLayout_48"))
        self.label_80 = QtGui.QLabel(self.page_16)
        self.label_80.setObjectName(_fromUtf8("label_80"))
        self.horizontalLayout_48.addWidget(self.label_80)
        self.spinBox_34 = QtGui.QSpinBox(self.page_16)
        self.spinBox_34.setObjectName(_fromUtf8("spinBox_34"))
        self.horizontalLayout_48.addWidget(self.spinBox_34)
        spacerItem11 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_48.addItem(spacerItem11)
        self.verticalLayout_21.addLayout(self.horizontalLayout_48)
        self.toolBox_2.addItem(self.page_16, _fromUtf8(""))
        self.verticalLayout_10.addWidget(self.toolBox_2)
        self.horizontalLayout_49 = QtGui.QHBoxLayout()
        self.horizontalLayout_49.setObjectName(_fromUtf8("horizontalLayout_49"))
        spacerItem12 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_49.addItem(spacerItem12)
        self.pushButton_4 = QtGui.QPushButton(self.frame_3)
        self.pushButton_4.setObjectName(_fromUtf8("pushButton_4"))
        self.horizontalLayout_49.addWidget(self.pushButton_4)
        spacerItem13 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_49.addItem(spacerItem13)
        self.verticalLayout_10.addLayout(self.horizontalLayout_49)
        self.verticalLayout_24.addWidget(self.frame_3)
        self.horizontalLayout_53.addLayout(self.verticalLayout_24)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1098, 22))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.toolBox.setCurrentIndex(3)
        self.stackedWidget.setCurrentIndex(1)
        self.tabWidget.setCurrentIndex(1)
        self.toolBox_2.setCurrentIndex(3)
        self.stackedWidget_2.setCurrentIndex(1)
        self.tabWidget_2.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.label_39.setText(QtGui.QApplication.translate("MainWindow", "Signal Generation", None, QtGui.QApplication.UnicodeUTF8))
        self.label_28.setText(QtGui.QApplication.translate("MainWindow", "Input Device", None, QtGui.QApplication.UnicodeUTF8))
        self.label_27.setText(QtGui.QApplication.translate("MainWindow", "Output Device", None, QtGui.QApplication.UnicodeUTF8))
        self.label_37.setText(QtGui.QApplication.translate("MainWindow", "Gain", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_5), QtGui.QApplication.translate("MainWindow", "Device Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(0, QtGui.QApplication.translate("MainWindow", "Swept Sine", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(1, QtGui.QApplication.translate("MainWindow", "Low Pass Swept Sine", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(2, QtGui.QApplication.translate("MainWindow", "Maximum Length Sequence", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(3, QtGui.QApplication.translate("MainWindow", "Inverse Repeat Sequence", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Start Frequency", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Hz", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "End Frequency", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "Hz", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("MainWindow", "Signal Length", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("MainWindow", "ms", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("MainWindow", "Signal Length", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("MainWindow", "ms", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("MainWindow", "Filter Cut Off", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("MainWindow", "Hz", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("MainWindow", "Filter Order", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("MainWindow", "Taps", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("MainWindow", "Repetitions", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setText(QtGui.QApplication.translate("MainWindow", "Signal Length", None, QtGui.QApplication.UnicodeUTF8))
        self.label_19.setText(QtGui.QApplication.translate("MainWindow", "ms", None, QtGui.QApplication.UnicodeUTF8))
        self.label_22.setText(QtGui.QApplication.translate("MainWindow", "Taps", None, QtGui.QApplication.UnicodeUTF8))
        self.label_20.setText(QtGui.QApplication.translate("MainWindow", "Repetitions", None, QtGui.QApplication.UnicodeUTF8))
        self.label_24.setText(QtGui.QApplication.translate("MainWindow", "Signal Length", None, QtGui.QApplication.UnicodeUTF8))
        self.label_25.setText(QtGui.QApplication.translate("MainWindow", "ms", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_6), QtGui.QApplication.translate("MainWindow", "Signal Properties", None, QtGui.QApplication.UnicodeUTF8))
        self.label_26.setText(QtGui.QApplication.translate("MainWindow", "Filter Cut Off", None, QtGui.QApplication.UnicodeUTF8))
        self.label_29.setText(QtGui.QApplication.translate("MainWindow", "Hz", None, QtGui.QApplication.UnicodeUTF8))
        self.label_30.setText(QtGui.QApplication.translate("MainWindow", "Filter Order", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtGui.QApplication.translate("MainWindow", "High Pass", None, QtGui.QApplication.UnicodeUTF8))
        self.label_32.setText(QtGui.QApplication.translate("MainWindow", "Filter Cut Off", None, QtGui.QApplication.UnicodeUTF8))
        self.label_33.setText(QtGui.QApplication.translate("MainWindow", "Hz", None, QtGui.QApplication.UnicodeUTF8))
        self.label_34.setText(QtGui.QApplication.translate("MainWindow", "Filter Order", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtGui.QApplication.translate("MainWindow", "Low Pass", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_7), QtGui.QApplication.translate("MainWindow", "Filter Properties", None, QtGui.QApplication.UnicodeUTF8))
        self.label_36.setText(QtGui.QApplication.translate("MainWindow", "Measurement Name", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Output Directory", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton.setText(QtGui.QApplication.translate("MainWindow", "Select...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_38.setText(QtGui.QApplication.translate("MainWindow", "Repetitions", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_8), QtGui.QApplication.translate("MainWindow", "Measurement Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_2.setText(QtGui.QApplication.translate("MainWindow", "Start Measurement", None, QtGui.QApplication.UnicodeUTF8))
        self.label_82.setText(QtGui.QApplication.translate("MainWindow", "Graphs", None, QtGui.QApplication.UnicodeUTF8))
        self.label_40.setText(QtGui.QApplication.translate("MainWindow", "Cepstrum", None, QtGui.QApplication.UnicodeUTF8))
        self.label_41.setText(QtGui.QApplication.translate("MainWindow", "Sample\'s Impulse Response", None, QtGui.QApplication.UnicodeUTF8))
        self.label_42.setText(QtGui.QApplication.translate("MainWindow", "Absorption Coefficient", None, QtGui.QApplication.UnicodeUTF8))
        self.label_81.setText(QtGui.QApplication.translate("MainWindow", "Signal Analysis", None, QtGui.QApplication.UnicodeUTF8))
        self.label_43.setText(QtGui.QApplication.translate("MainWindow", "Input Device", None, QtGui.QApplication.UnicodeUTF8))
        self.label_44.setText(QtGui.QApplication.translate("MainWindow", "Output Device", None, QtGui.QApplication.UnicodeUTF8))
        self.label_45.setText(QtGui.QApplication.translate("MainWindow", "Gain", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBox_2.setItemText(self.toolBox_2.indexOf(self.page_9), QtGui.QApplication.translate("MainWindow", "Device Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_6.setItemText(0, QtGui.QApplication.translate("MainWindow", "Swept Sine", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_6.setItemText(1, QtGui.QApplication.translate("MainWindow", "Low Pass Swept Sine", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_6.setItemText(2, QtGui.QApplication.translate("MainWindow", "Maximum Length Sequence", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_6.setItemText(3, QtGui.QApplication.translate("MainWindow", "Inverse Repeat Sequence", None, QtGui.QApplication.UnicodeUTF8))
        self.label_46.setText(QtGui.QApplication.translate("MainWindow", "Start Frequency", None, QtGui.QApplication.UnicodeUTF8))
        self.label_47.setText(QtGui.QApplication.translate("MainWindow", "Hz", None, QtGui.QApplication.UnicodeUTF8))
        self.label_48.setText(QtGui.QApplication.translate("MainWindow", "End Frequency", None, QtGui.QApplication.UnicodeUTF8))
        self.label_49.setText(QtGui.QApplication.translate("MainWindow", "Hz", None, QtGui.QApplication.UnicodeUTF8))
        self.label_50.setText(QtGui.QApplication.translate("MainWindow", "Signal Length", None, QtGui.QApplication.UnicodeUTF8))
        self.label_51.setText(QtGui.QApplication.translate("MainWindow", "ms", None, QtGui.QApplication.UnicodeUTF8))
        self.label_52.setText(QtGui.QApplication.translate("MainWindow", "Signal Length", None, QtGui.QApplication.UnicodeUTF8))
        self.label_53.setText(QtGui.QApplication.translate("MainWindow", "ms", None, QtGui.QApplication.UnicodeUTF8))
        self.label_54.setText(QtGui.QApplication.translate("MainWindow", "Filter Cut Off", None, QtGui.QApplication.UnicodeUTF8))
        self.label_55.setText(QtGui.QApplication.translate("MainWindow", "Hz", None, QtGui.QApplication.UnicodeUTF8))
        self.label_56.setText(QtGui.QApplication.translate("MainWindow", "Filter Order", None, QtGui.QApplication.UnicodeUTF8))
        self.label_58.setText(QtGui.QApplication.translate("MainWindow", "Taps", None, QtGui.QApplication.UnicodeUTF8))
        self.label_60.setText(QtGui.QApplication.translate("MainWindow", "Repetitions", None, QtGui.QApplication.UnicodeUTF8))
        self.label_62.setText(QtGui.QApplication.translate("MainWindow", "Signal Length", None, QtGui.QApplication.UnicodeUTF8))
        self.label_63.setText(QtGui.QApplication.translate("MainWindow", "ms", None, QtGui.QApplication.UnicodeUTF8))
        self.label_64.setText(QtGui.QApplication.translate("MainWindow", "Taps", None, QtGui.QApplication.UnicodeUTF8))
        self.label_66.setText(QtGui.QApplication.translate("MainWindow", "Repetitions", None, QtGui.QApplication.UnicodeUTF8))
        self.label_68.setText(QtGui.QApplication.translate("MainWindow", "Signal Length", None, QtGui.QApplication.UnicodeUTF8))
        self.label_69.setText(QtGui.QApplication.translate("MainWindow", "ms", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBox_2.setItemText(self.toolBox_2.indexOf(self.page_10), QtGui.QApplication.translate("MainWindow", "Signal Properties", None, QtGui.QApplication.UnicodeUTF8))
        self.label_70.setText(QtGui.QApplication.translate("MainWindow", "Filter Cut Off", None, QtGui.QApplication.UnicodeUTF8))
        self.label_71.setText(QtGui.QApplication.translate("MainWindow", "Hz", None, QtGui.QApplication.UnicodeUTF8))
        self.label_72.setText(QtGui.QApplication.translate("MainWindow", "Filter Order", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_3), QtGui.QApplication.translate("MainWindow", "High Pass", None, QtGui.QApplication.UnicodeUTF8))
        self.label_74.setText(QtGui.QApplication.translate("MainWindow", "Filter Cut Off", None, QtGui.QApplication.UnicodeUTF8))
        self.label_75.setText(QtGui.QApplication.translate("MainWindow", "Hz", None, QtGui.QApplication.UnicodeUTF8))
        self.label_76.setText(QtGui.QApplication.translate("MainWindow", "Filter Order", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_4), QtGui.QApplication.translate("MainWindow", "Low Pass", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBox_2.setItemText(self.toolBox_2.indexOf(self.page_15), QtGui.QApplication.translate("MainWindow", "Filter Properties", None, QtGui.QApplication.UnicodeUTF8))
        self.label_78.setText(QtGui.QApplication.translate("MainWindow", "Measurement Name", None, QtGui.QApplication.UnicodeUTF8))
        self.label_79.setText(QtGui.QApplication.translate("MainWindow", "Output Directory", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_3.setText(QtGui.QApplication.translate("MainWindow", "Select...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_80.setText(QtGui.QApplication.translate("MainWindow", "Repetitions", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBox_2.setItemText(self.toolBox_2.indexOf(self.page_16), QtGui.QApplication.translate("MainWindow", "Measurement Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_4.setText(QtGui.QApplication.translate("MainWindow", "Start Measurement", None, QtGui.QApplication.UnicodeUTF8))

from matplotlibwidget import MatplotlibWidget
